"""create stock alerts table

Revision ID: d6beaad55169
Revises: e7fbc8224ca5
Create Date: 2026-03-24 14:54:51.908410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6beaad55169'
down_revision: Union[str, Sequence[str], None] = 'e7fbc8224ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', name='uq_alertas_stock_producto_id')
    )
    op.create_index(op.f('ix_alertas_stock_id'), 'alertas_stock', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alertas_stock_id'), table_name='alertas_stock')
    op.drop_table('alertas_stock')
    # ### end Alembic commands ###
