"""create inventory movements table

Revision ID: e7fbc8224ca5
Revises: 7425ad057307
Create Date: 2026-03-16 16:48:50.230996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7fbc8224ca5'
down_revision: Union[str, Sequence[str], None] = '7425ad057307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_operacion', sa.String(length=50), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.String(length=50), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_inventario_id'), 'movimientos_inventario', ['id'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_id_operacion'), 'movimientos_inventario', ['id_operacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_inventario_id_operacion'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_id'), table_name='movimientos_inventario')
    op.drop_table('movimientos_inventario')
    # ### end Alembic commands ###
